name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: store_db
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="echo 'db.runCommand(\"ping\").ok' | mongosh --quiet"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Créer fichier .env
        run: |
          echo "MYSQL_HOST=127.0.0.1" >> .env
          echo "MYSQL_DB_NAME=store_db" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=pass" >> .env
          echo "MONGODB_HOST=127.0.0.1" >> .env
          echo "MONGODB_PORT=27017" >> .env
          echo "MONGODB_DATABASE=store_db" >> .env

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for MySQL and init schema
        run: |
          sudo apt-get install -y mysql-client
          for i in {1..10}; do
            mysql -h 127.0.0.1 -uuser -ppass store_db < db-init/init.sql && break
            echo " MySQL not ready yet, retrying..."
            sleep 5
          done

      - name: Exécuter les tests avec PYTHONPATH
        run: PYTHONPATH=src pytest -q
